(function(){function e(e){return e}var t=e({matches:[`*://*.tiktok.com/*`],world:`MAIN`,main(){console.log(`[DUZKVIDEOTOOL] TikTok Content Script Initialized`);let e=``;function t(){let t=window.location.href;if(!t.includes(`/video/`)&&!t.includes(`/photo/`)||t===e&&document.querySelector(`.duzk-tiktok-toolbar`))return;e=t;let r=document.querySelector(`[data-e2e="feed-video-container"], .tiktok-player, [data-e2e="browse-video-container"], [class*="DivVideoContainer"]`)||document.body,i=document.querySelector(`[data-e2e="browse-video-desc"], [data-e2e="user-post-item-desc"]`);n(r,t,i?i.textContent?.trim():document.title)}function n(e,t,n){if(!e)return;let r=document.querySelector(`.duzk-tiktok-toolbar`);r&&r.remove();let i=document.createElement(`div`);i.className=`duzk-tiktok-toolbar`,i.style.cssText=`
        position: absolute;
        top: 20px;
        right: 20px;
        z-index: 999999;
        display: flex;
        align-items: center;
        gap: 8px;
        background: rgba(18, 18, 18, 0.92);
        backdrop-filter: blur(14px);
        -webkit-backdrop-filter: blur(14px);
        padding: 6px 12px;
        border-radius: 24px;
        border: 1px solid rgba(254, 44, 85, 0.4);
        box-shadow: 0 8px 32px rgba(0, 0, 0, 0.7);
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      `;let a=document.createElement(`button`);a.innerHTML=`⚡ Lồng Tiếng AI`,a.style.cssText=`
        background: linear-gradient(135deg, #FE2C55 0%, #25F4EE 100%);
        color: #000000;
        font-weight: 800;
        font-size: 12px;
        padding: 6px 14px;
        border-radius: 16px;
        border: none;
        cursor: pointer;
        transition: transform 0.15s ease;
      `,a.onmouseenter=()=>{a.style.transform=`scale(1.05)`},a.onmouseleave=()=>{a.style.transform=`scale(1.0)`},a.onclick=e=>{e.stopPropagation();let n=`http://localhost:5000/?url=${encodeURIComponent(t)}&autoExtract=1`;window.open(n,`_blank`)};let o=document.createElement(`button`);o.innerHTML=`💎 Tải HD/MP3 ▼`,o.style.cssText=`
        background: rgba(255, 255, 255, 0.12);
        color: #FFFFFF;
        font-weight: 700;
        font-size: 11px;
        padding: 6px 12px;
        border-radius: 16px;
        border: 1px solid rgba(255, 255, 255, 0.2);
        cursor: pointer;
      `;let s=document.createElement(`div`);s.style.cssText=`
        position: absolute;
        top: 42px;
        right: 0;
        background: rgba(18, 18, 18, 0.96);
        backdrop-filter: blur(20px);
        -webkit-backdrop-filter: blur(20px);
        border: 1px solid rgba(254, 44, 85, 0.4);
        border-radius: 12px;
        padding: 8px;
        display: none;
        flex-direction: column;
        gap: 6px;
        min-width: 180px;
        box-shadow: 0 10px 30px rgba(0, 0, 0, 0.8);
        z-index: 1000000;
      `;let c=!1,l=null;o.onclick=async e=>{if(e.stopPropagation(),c){s.style.display=`none`,c=!1;return}s.innerHTML=`<div style="color:#aaa;font-size:11px;padding:6px;text-align:center;">⏳ Đang bóc tách...</div>`,s.style.display=`flex`,c=!0;try{if(!l){let e=await(await fetch(`http://localhost:5000/api/extract`,{method:`POST`,headers:{"Content-Type":`application/json`},body:JSON.stringify({url:t})})).json();if(!e.ok)throw Error(e.error);l=e.data}s.innerHTML=``;let e=(n||`tiktok_video`).replace(/[/\\?%*:|"<>]/g,`_`).slice(0,40);if(l.videoUrl){let t=document.createElement(`a`);t.href=`http://localhost:5000/api/proxy-media?url=${encodeURIComponent(l.videoUrl)}&download=1&filename=${encodeURIComponent(e+`.mp4`)}`,t.target=`_blank`,t.innerHTML=`<span>📥 Tải Video Không Logo HD</span>`,t.style.cssText=`
              color: #00F2FE;
              font-size: 11px;
              font-weight: 700;
              text-decoration: none;
              padding: 6px 10px;
              border-radius: 6px;
              background: rgba(0, 242, 254, 0.1);
              display: flex;
              justify-content: space-between;
              align-items: center;
            `,t.onclick=e=>{e.stopPropagation(),s.style.display=`none`,c=!1},s.appendChild(t)}if(l.musicUrl){let t=document.createElement(`a`);t.href=`http://localhost:5000/api/proxy-media?url=${encodeURIComponent(l.musicUrl)}&download=1&filename=${encodeURIComponent(e+`_audio.mp3`)}`,t.target=`_blank`,t.innerHTML=`<span>🎵 Tải Audio MP3 Gốc</span>`,t.style.cssText=`
              color: #FFE500;
              font-size: 11px;
              font-weight: 700;
              text-decoration: none;
              padding: 6px 10px;
              border-radius: 6px;
              background: rgba(255, 229, 0, 0.1);
              display: flex;
              justify-content: space-between;
              align-items: center;
            `,t.onclick=e=>{e.stopPropagation(),s.style.display=`none`,c=!1},s.appendChild(t)}}catch(e){s.innerHTML=`<div style="color:#F87171;font-size:11px;padding:6px;">⚠️ Lỗi: ${e.message}</div>`}},document.addEventListener(`click`,e=>{i.contains(e.target)||(s.style.display=`none`,c=!1)}),i.appendChild(a),i.appendChild(o),i.appendChild(s),e.style&&getComputedStyle(e).position===`static`&&(e.style.position=`relative`),e.appendChild(i)}setInterval(t,1e3)}}),n={debug:(...e)=>([...e],void 0),log:(...e)=>([...e],void 0),warn:(...e)=>([...e],void 0),error:(...e)=>([...e],void 0)};return(async()=>{try{return await t.main()}catch(e){throw n.error(`The content script "tiktok" crashed on startup!`,e),e}})()})();