(function(){function e(e){return e}var t=e({matches:[`*://*.xiaohongshu.com/*`],world:`MAIN`,main(){console.log(`[DUZKVIDEOTOOL] Xiaohongshu Content Script Initialized`);let e=new Map;function t(){document.querySelectorAll(`.note-container, .modal-container, .feed-card, .feeds-container .note-item, section.note-item`).forEach((t,r)=>{let i=t.querySelector(`video`),a=t.querySelector(`.title, .note-title, #detail-title, .desc, .content, .footer .title`),o=t.querySelector(`.author, .name, .author-wrapper .name, .user-name, .author-container .name`),s=t.querySelector(`.avatar img, .user-avatar img, .author-wrapper img`),c=a?a.textContent?.trim():`Xiaohongshu Post #${r+1}`,l=o?o.textContent?.trim():`XHS Creator`,u=s?s.src:``,d=window.location.href,f=d.match(/explore\/([a-zA-Z0-9]+)/)||d.match(/discovery\/item\/([a-zA-Z0-9]+)/),p=f?f[1]:t.getAttribute(`data-id`)||`xhs_${r}_${Date.now()}`,m=i?i.src||i.currentSrc:``;e.has(p)||e.set(p,{id:p,platform:`xiaohongshu`,title:c,author:l,authorAvatar:u,mediaUrl:m,pageUrl:d,likes:0,comments:0}),n(t,d,p,c)}),document.querySelectorAll(`video`).forEach((e,t)=>{let r=e.closest(`.note-container`)||e.closest(`.modal-container`)||e.parentElement;r&&n(r,window.location.href,`xhs_vid_${t}`,document.title)})}function n(e,t,n,r){if(!e||e.querySelector(`.duzk-xhs-toolbar`))return;let i=document.createElement(`div`);i.className=`duzk-xhs-toolbar`,i.style.cssText=`
        position: absolute;
        top: 12px;
        right: 12px;
        z-index: 9999;
        display: flex;
        align-items: center;
        gap: 6px;
        background: rgba(10, 15, 26, 0.92);
        backdrop-filter: blur(14px);
        -webkit-backdrop-filter: blur(14px);
        padding: 5px 10px;
        border-radius: 20px;
        border: 1px solid rgba(254, 44, 85, 0.4);
        box-shadow: 0 6px 24px rgba(0, 0, 0, 0.6);
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      `;let a=document.createElement(`button`);a.innerHTML=`⚡ Lồng Tiếng AI`,a.title=`Mở bài viết này trong DUZK Video Studio`,a.style.cssText=`
        background: linear-gradient(135deg, #FE2C55 0%, #FF5277 100%);
        color: #ffffff;
        font-weight: 800;
        font-size: 11px;
        padding: 5px 12px;
        border-radius: 14px;
        border: none;
        cursor: pointer;
        transition: transform 0.15s ease;
      `,a.onmouseenter=()=>{a.style.transform=`scale(1.05)`},a.onmouseleave=()=>{a.style.transform=`scale(1)`},a.onclick=e=>{e.stopPropagation(),e.preventDefault();let i=encodeURIComponent(JSON.stringify({platform:`xiaohongshu`,id:n,title:r,pageUrl:t}));window.open(`http://localhost:5000/?url=${encodeURIComponent(t)}&data=${i}`,`_blank`)};let o=document.createElement(`button`);o.innerHTML=`💎 Tải HD/Ảnh ▼`,o.style.cssText=`
        background: rgba(255, 255, 255, 0.12);
        color: #ffffff;
        font-weight: 700;
        font-size: 11px;
        padding: 5px 10px;
        border-radius: 14px;
        border: 1px solid rgba(255, 255, 255, 0.25);
        cursor: pointer;
      `;let s=document.createElement(`div`);s.style.cssText=`
        position: absolute;
        top: 38px;
        right: 0;
        background: rgba(10, 15, 26, 0.96);
        backdrop-filter: blur(20px);
        -webkit-backdrop-filter: blur(20px);
        border: 1px solid rgba(254, 44, 85, 0.4);
        border-radius: 12px;
        padding: 8px;
        display: none;
        flex-direction: column;
        gap: 6px;
        min-width: 190px;
        box-shadow: 0 10px 30px rgba(0, 0, 0, 0.8);
        z-index: 1000000;
      `;let c=!1,l=null;o.onclick=async e=>{if(e.stopPropagation(),e.preventDefault(),c){s.style.display=`none`,c=!1;return}s.innerHTML=`<div style="color:#aaa;font-size:11px;padding:6px;text-align:center;">⏳ Đang quét bài viết...</div>`,s.style.display=`flex`,c=!0;try{if(!l){let e=await(await fetch(`http://localhost:5000/api/extract`,{method:`POST`,headers:{"Content-Type":`application/json`},body:JSON.stringify({url:t})})).json();if(!e.ok)throw Error(e.error);l=e.data}if(s.innerHTML=``,l.videoUrl&&(l.qualities||[{label:`1080p (Full HD)`,url:l.videoUrl}]).forEach(e=>{let t=document.createElement(`a`);t.href=`http://localhost:5000/api/proxy-media?url=${encodeURIComponent(e.url)}&download=1&filename=${encodeURIComponent((r||`xhs_video`).slice(0,30)+`_${e.label.replace(/[^\w]/g,`_`)}.mp4`)}`,t.target=`_blank`,t.innerHTML=`<span>📹 Tải ${e.label}</span> <span style="opacity:0.6;font-size:10px;">${e.resolution||``}</span>`,t.style.cssText=`
                color: #fff;
                font-size: 11px;
                font-weight: 600;
                text-decoration: none;
                padding: 6px 10px;
                border-radius: 6px;
                background: rgba(255,255,255,0.06);
                display: flex;
                justify-content: space-between;
                align-items: center;
              `,t.onclick=e=>{e.stopPropagation(),s.style.display=`none`,c=!1},s.appendChild(t)}),l.images&&l.images.length>0){let e=document.createElement(`button`);e.innerHTML=`<span>🖼️ Tải Tất Cả ${l.images.length} Ảnh HD</span>`,e.style.cssText=`
              color: #00F2FE;
              font-size: 11px;
              font-weight: 700;
              padding: 6px 10px;
              border-radius: 6px;
              border: none;
              background: rgba(0, 242, 254, 0.15);
              cursor: pointer;
              display: flex;
              justify-content: space-between;
              align-items: center;
            `,e.onclick=e=>{e.stopPropagation(),l.images.forEach((e,t)=>{let n=`http://localhost:5000/api/proxy-media?url=${encodeURIComponent(e)}&download=1&filename=xhs_img_${t+1}.jpg`;window.open(n,`_blank`)}),s.style.display=`none`,c=!1},s.appendChild(e)}}catch(e){s.innerHTML=`<div style="color:#F87171;font-size:11px;padding:6px;">⚠️ Lỗi: ${e.message}<br/>Hãy bật Server DUZK tại port 5000</div>`}},document.addEventListener(`click`,e=>{i.contains(e.target)||(s.style.display=`none`,c=!1)}),i.appendChild(a),i.appendChild(o),i.appendChild(s),window.getComputedStyle(e).position===`static`&&(e.style.position=`relative`),e.appendChild(i)}setInterval(t,2500),t()}}),n={debug:(...e)=>([...e],void 0),log:(...e)=>([...e],void 0),warn:(...e)=>([...e],void 0),error:(...e)=>([...e],void 0)};return(async()=>{try{return await t.main()}catch(e){throw n.error(`The content script "xiaohongshu" crashed on startup!`,e),e}})()})();